# Generated by Django 4.0.3 on 2022-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
